version: '3.8'
services:
  app:
    # コンテナの名前を設定
    container_name: backend-graphql-todo-app
    # 同ディレクトリ内のDockerfileを参照してビルドを行う
    build: .
    # ローカルPCのbackend-graphql-todoディレクトリとDockerコンテナ内のbackend-graphql-todoディレクトリを同期させる
    volumes:
      - .:/backend-graphql-todo
    # コンテナが立ち上がったときに下記コマンドを実行する（Dockerfileに書かれたものより優先される）
    command: npm run start:dev
    # ローカルPCの8080番ポートとDockerコンテナの8080番ポートを接続する
    ports:
      # nestアプリケーションにつながるポート
      - 8080:8080
      # prisma studioにつながるポート
      - 5555:5555
    # 利用するDockerNetworkを指定
    networks:
      - backend-graphql-todo-nw
    # dbコンテナ起動後にappコンテナを起動させる
    depends_on:
      - db
  db:
    # 公式のイメージを利用(M1チップ用)
    image: arm64v8/mysql:8.0
    # IntelチップのMacでは以下のimageを指定する
    # image: mysql:8.0

    # コンテナの名前を設定
    container_name: backend-graphql-todo-db
    # ローカルPCの3307番ポートとDockerコンテナの3306番ポートを接続する
    ports:
      - 3307:3306
    # DBに設定する値
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend-graphql-todo-db
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    # DBのデータをvolumeに移しデータを永続化する
    volumes:
      - backend-graphql-todo-volume:/var/lib/mysql
    # 利用するDockerNetworkを指定
    networks:
      - backend-graphql-todo-nw
# Docker上で本コンテナが設置されるNetworkを作成
networks:
  backend-graphql-todo-nw:
# MySQLに保存したデータを永続化する場所
volumes:
  backend-graphql-todo-volume:
